/* This file autogenerated by src/common/Makefile */
char *default_plugin_path = "/home/marcodamico/slurm-port_tools/install/slurm_programs/lib/slurm";
char *default_slurm_config_file = "/home/marcodamico/slurm-port_tools/install/slurm_conf/slurm.conf";
char *default_plugstack = "/home/marcodamico/slurm-port_tools/install/slurm_conf/plugstack.conf";
